### ISSUE TITLE
Unable to interact with top half of screen even with map in Pokeball mode.

### ISSUE THREAD

**Issue by Kairnth** [benjy3gg/pokeRadar#3]
Unable to interact with top half of screen even with map in Pokeball mode.

Asus Zenfone 2
Android 5.0

**Comment by ChiIIerr** [comment]
Having the same issue

Samsung Galaxy S6
Android 5.1.1

**Comment by benjy3gg** [comment]
which version did you try?
https://github.com/benjy3gg/pokeRadar/releases/tag/0.2 should fix this

**Comment by ChiIIerr** [comment]
Still having the issue even with the current version sadly D:
